config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :goals
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  user_id      :integer          not null
#  status       :string           not null
#  private_goal :boolean          default(FALSE), not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Goal < ActiveRecord::Base
  validates :user, :status, :title, :description, presence: true
  validates :status, inclusion: %w(active completed)
  validates :private_goal, inclusion: [true, false]
  belongs_to :user, inverse_of: :goals
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :username, uniqueness: true
  attr_reader :password
  after_initialize :ensure_session_token!

  has_many :goals, inverse_of: :user

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private

  def ensure_session_token!
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :ensure_signed_in!

  def signin!(user)
    session[:session_token] = user.reset_session_token!
  end

  def signout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def ensure_signed_in!
    redirect_to new_session_url unless current_user
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :ensure_signed_in!

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user

    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])

    if @goal.user == current_user || @goal.private_goal == false
      render :show
    else
      redirect_to goals_url
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    if @goal.user == current_user
      render :edit
    else
      redirect_to goals_url
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    user = @goal.user
    if @goal.user == current_user
      @goal.destroy
      redirect_to user_url(user)
    else
      redirect_to goals_url
    end
  end


  def update
    @goal = Goal.find(params[:id])
    # debugger if goal_params[:title] == "New goal title"

    if current_user != @goal.user
      redirect_to goals_url
    elsif @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def index

    @goals = Goal.where(private_goal: false)
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :description, :status, :private_goal)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      signin!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    signout!
    redirect_to new_session_url
  end

  private

  def session_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      signin!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_token
    "<input type='hidden'
            name='authenticity_token'
            value='#{form_authenticity_token}'>".html_safe
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<h1>All Goals</h1>

<ul>
  <% @goals.each do |goal| %>
  <%= link_to(goal.title, goal_url(goal)) %>
  <% end %>
</ul>

<%= link_to("Create a new goal", new_goal_url) %>

app/views/goals/new.html.erb
<h2> Create a new goal!</h2>
<form action="<%= goals_url %>" method="post">
  <%= form_token %>
  <label>Title
    <input type="text" name="goal[title]" value="<%= @goal.title %>">
  </label>
  <label>Description
    <textarea name="goal[description]" rows="8" cols="40"><%= @goal.description %></textarea>
  </label>

  <label>Status
    <select name="goal[status]" id="StatusSelect">
    <option value="active">Active</option>
    <option value="completed">Completed</option>
    </select>
  </label>

  <label>Privacy
    <label>Private<input type="radio" name="goal[private_goal]" value="true"></label>
    <label>Public<input type="radio" name="goal[private_goal]" value="false"></label>
  </label>
  <input type="submit" value="Create New Goal">
</form>

app/views/goals/show.html.erb
<%= @goal.title %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CapyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <% if flash[:errors] %>
  <%= flash[:errors].join(', ') %>
  <% end %>
  <% if current_user %>
    <p>
      Signed in as: <%= current_user.username %>
    </p>

    <%= button_to("Sign Out", session_url, method: :delete) %>
  <% end %>
</header>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>New User</h2>

<form action="<%= users_url %>" method="POST">
  <%= form_token %>
  <label>Username <input type="text" name="user[username]" value="<%= @user.username %>"></label>
  <label>Password <input type="password" name="user[password]" value=""></label>

  <input type="submit" value="Create User">
</form>

app/views/users/show.html.erb
<%= button_to "Create New Goal", new_goal_url, method: :get %>